/*
 * FRANK universal test firmware
 *
 * Copyright (c) 2026 Mikhail Matveev <xtreme@rh1.tech>
 * https://github.com/rh1tech/frank-test
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * ui_video_pio_hdmi.c — HDMI out of the PIO, for boards HSTX cannot reach.
 *
 *
 * WHY A SECOND HDMI BACKEND
 *
 * HSTX is wired to GP12-19 and nowhere else. That is fine for every
 * FRANK board, which is why this firmware had one HDMI path — and it is
 * not fine for the Waveshare RP2350-PiZero, whose connector is on
 * GP32-39. On that board the HSTX driver clocks TMDS out of pins joined
 * to nothing while the socket stays dark.
 *
 * So the signal is generated by PIO instead, from murmnes' driver, which
 * already drives exactly this board. Two backends claim the same mode
 * and each refuses the boards it cannot serve, which is why they can sit
 * in the same table: ui_video_open() takes the first whose init()
 * agrees.
 *
 *
 * IT DRAWS A TEXT PAGE, NOT THE DESKTOP
 *
 * The driver scans a 320x240 indexed framebuffer doubled to 640x480, so
 * there is a quarter of the desktop's pixels to work with. Scaling
 * 6-pixel type by a half is a grey smear, and a rig whose results cannot
 * be read is not reporting anything — the same argument composite
 * settled, and the same answer: ui_textpage.c draws the interface at
 * native resolution, 53 columns by 30 rows here.
 *
 * That is also why the menus and dialogs come through. Without them an
 * unidentified board would have no way to reach Set Board, and nothing
 * could be run at all.
 *
 *
 * WHERE THE FRAME LIVES
 *
 * Borrowed, exactly as composite borrows it. Two 4 bpp screen buffers
 * already hold 307,200 bytes of the RP2350's 520 KB and another 76,800
 * does not fit. This backend never scans our buffers, so one of the
 * double-buffered pair is doing nothing and that is where the page goes.
 * The cost is that this path must never swap them, and it has no reason
 * to: there is no vertical blank here to swap at.
 */

#include "ui_video.h"

#include "ui_desktop.h"
#include "ui_gfx.h"
#include "ui_palette.h"
#include "ui_textpage.h"

#include "hdmi.h"

#include "pico/multicore.h"
#include "pico/stdlib.h"

#include <string.h>

#define PIO_W 320
#define PIO_H 240

static uint8_t *page;
static int      s_video_base = 12;

/* main() says where this board's video pins are, because the two HDMI
 * backends are told apart by nothing else. */
void ui_video_pio_set_base(int base) { s_video_base = base; }
int  ui_video_pio_base(void)         { return s_video_base; }

volatile uint32_t ui_pio_hdmi_frames;

/* Core 1 runs the scanline interrupt, as it does on every other video
 * path here. */
static void __not_in_flash_func(pio_core1_run)(void) {
    graphics_init_hdmi();
    while (true) tight_loop_contents();
}

static bool pio_hdmi_init(void) {
    /* Only where HSTX cannot do the job. On a board wired to GP12-19 the
     * HSTX backend is better in every way - hardware TMDS rather than a
     * PIO program and a core - and it sits earlier in the table, so this
     * refusing is what picks the right one. */
    if (s_video_base < 32) return false;

    extern uint8_t *ui_video_spare_bits(void);
    page = ui_video_spare_bits();
    memset(page, 0, (size_t)PIO_W * PIO_H);

    graphics_set_res(PIO_W, PIO_H);
    graphics_set_buffer(page);
    ui_textpage_target(page, PIO_W, PIO_H);

    /* The interface's own palette, straight in: this driver is indexed
     * and takes RGB888 per entry, which is what ui_palette holds. */
    for (unsigned i = 0; i < UI_PALETTE_LEN; i++)
        graphics_set_palette_hdmi((uint8_t)i, ui_palette_rgb888[i]);

    multicore_reset_core1();
    multicore_launch_core1(pio_core1_run);
    return true;
}

static void pio_hdmi_present(void) {
    /* Nothing to synchronise with. The driver owns the frame and reads
     * it on its own schedule, so this simply rewrites it - and with no
     * moving content between frames, a tear at pixel granularity is not
     * visible. Composite makes the same trade for the same reason. */
    if (ui_textpage_ready()) ui_textpage_draw();
    ui_pio_hdmi_frames++;
}

static uint32_t pio_hdmi_frames(void) { return ui_pio_hdmi_frames; }

const ui_video_backend_t ui_video_backend_pio_hdmi = {
    .name     = "PIO HDMI 640x480",
    .mode     = VIDEO_HDMI,
    .init     = pio_hdmi_init,
    /* No shutdown, for the same reason as the others: unwinding the DMA
     * chain, the exclusive handler and core 1 is more risk than the
     * reboot ui_video_switch() does instead. */
    .shutdown = NULL,
    .present  = pio_hdmi_present,
    .frames   = pio_hdmi_frames,
};
