/*
 * FRANK universal test firmware
 *
 * Copyright (c) 2026 Mikhail Matveev <xtreme@rh1.tech>
 * https://github.com/rh1tech/frank-test
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * ui_video_pio_hdmi.c — HDMI out of the PIO, for boards HSTX cannot reach.
 *
 *
 * WHY A SECOND HDMI BACKEND
 *
 * HSTX is wired to GP12-19 and nowhere else. That is fine for every
 * FRANK board, which is why this firmware had one HDMI path — and it is
 * not fine for the Waveshare RP2350-PiZero, whose connector is on
 * GP32-39. On that board the HSTX driver clocks TMDS out of pins joined
 * to nothing while the socket stays dark.
 *
 * So the signal is generated by PIO instead, from murmnes' driver, which
 * already drives exactly this board. Two backends claim the same mode
 * and each refuses the boards it cannot serve, which is why they can sit
 * in the same table: ui_video_open() takes the first whose init()
 * agrees.
 *
 *
 * IT DRAWS A TEXT PAGE, NOT THE DESKTOP
 *
 * The driver scans a 320x240 indexed framebuffer doubled to 640x480, so
 * there is a quarter of the desktop's pixels to work with. Scaling
 * 6-pixel type by a half is a grey smear, and a rig whose results cannot
 * be read is not reporting anything — the same argument composite
 * settled, and the same answer: ui_textpage.c draws the interface at
 * native resolution, 53 columns by 30 rows here.
 *
 * That is also why the menus and dialogs come through. Without them an
 * unidentified board would have no way to reach Set Board, and nothing
 * could be run at all.
 *
 *
 * WHERE THE FRAME LIVES
 *
 * Borrowed, exactly as composite borrows it. Two 4 bpp screen buffers
 * already hold 307,200 bytes of the RP2350's 520 KB and another 76,800
 * does not fit. This backend never scans our buffers, so one of the
 * double-buffered pair is doing nothing and that is where the pages go.
 *
 * Pages, plural: that spare buffer is 153,600 bytes and a page here is
 * 76,800, so both fit inside it and this path can flip between them.
 * That is not a luxury — every repaint starts by clearing the frame, and
 * with one page the display showed the clear, so the screen flashed on
 * each keypress.
 */

#include "ui_video.h"

#include "ui_desktop.h"
#include "ui_gfx.h"
#include "ui_palette.h"
#include "ui_textpage.h"

/* Path-qualified deliberately. drivers/ holds frank-msx's HDMI.h, and on
 * a case-insensitive filesystem - which macOS is by default - a plain
 * "hdmi.h" resolves to that one instead of the PIO driver's, since
 * drivers/ comes before drivers/hdmi_pio on the include path. It
 * declares enough of the same API to compile and quietly disagrees about
 * the rest, so the bug only shows on the bench and never in CI, which
 * builds on a case-sensitive filesystem and gets the right header. */
#include "hdmi_pio/hdmi.h"

#include "pico/multicore.h"
#include "pico/stdlib.h"

#include <string.h>

#define PIO_W 320
#define PIO_H 240

/* Both pages live inside the borrowed 4 bpp buffer. If the desktop ever
 * shrinks, this path silently scribbles past the end of it, so fail the
 * build instead. */
_Static_assert(2 * PIO_W * PIO_H <= UI_FB_BYTES,
               "PIO HDMI needs two pages inside one borrowed framebuffer");

static uint8_t *page;   /* what the driver is scanning */
static uint8_t *back;   /* what we are drawing */
static int      s_video_base = 12;

/* main() says where this board's video pins are, because the two HDMI
 * backends are told apart by nothing else. */
void ui_video_pio_set_base(int base) { s_video_base = base; }
int  ui_video_pio_base(void)         { return s_video_base; }

/* Core 1 runs the scanline interrupt, as it does on every other video
 * path here. */
static void __not_in_flash_func(pio_core1_run)(void) {
    graphics_init_hdmi();

    /* The palette goes in here rather than beside the rest of the setup,
     * because graphics_init_hdmi() clears all 256 entries to black and
     * reconverts them. Uploaded before the launch it is simply thrown
     * away, and the result is a picture drawn correctly in black on
     * black - a signal the display locks to, showing nothing, which
     * reads exactly like a driver that does not work. */
    for (unsigned i = 0; i < UI_PALETTE_LEN; i++)
        graphics_set_palette_hdmi((uint8_t)i, ui_palette_rgb888[i]);

    while (true) tight_loop_contents();
}

static bool pio_hdmi_init(void) {
    /* Only where HSTX cannot do the job. On a board wired to GP12-19 the
     * HSTX backend is better in every way - hardware TMDS rather than a
     * PIO program and a core - and it sits earlier in the table, so this
     * refusing is what picks the right one. */
    if (s_video_base < 32) return false;

    /* Two pages, both inside the borrowed buffer. It is a 640x480 4 bpp
     * screen - 153,600 bytes - and a page here is 320x240 at 8 bpp, so
     * two of them fit with room to spare. See pio_hdmi_present() for
     * why one is not enough. */
    extern uint8_t *ui_video_spare_bits(void);
    page = ui_video_spare_bits();
    back = page + (size_t)PIO_W * PIO_H;
    memset(page, 0, (size_t)PIO_W * PIO_H * 2);

    graphics_set_res(PIO_W, PIO_H);
    graphics_set_buffer(page);
    ui_textpage_target(back, PIO_W, PIO_H);

    /* The palette is loaded by core 1, after init - see pio_core1_run. */
    multicore_reset_core1();
    multicore_launch_core1(pio_core1_run);
    return true;
}

static void pio_hdmi_present(void) {
    /* Draw into the page the driver is not scanning, then hand it over.
     *
     * Drawing straight into the live page meant the display showed the
     * clear-to-black that starts every repaint, so the whole screen
     * flashed on each keypress. There is nothing to synchronise with
     * here - no vertical blank this side of the ISR - so the fix is to
     * make the visible page never be the one under construction.
     *
     * The swap itself is one pointer, which the ISR reads per scanline:
     * the worst case is a single frame split between two images that
     * differ by one highlighted row, and that is not visible. */
    if (!ui_textpage_ready()) return;

    ui_textpage_draw();

    uint8_t *shown = back;
    back = page;
    page = shown;

    graphics_set_buffer(shown);
    ui_textpage_target(back, PIO_W, PIO_H);
}

/* From the driver's ISR, not from present(): the Video output row is
 * asking whether frames reached the connector, and repaints are not
 * evidence of that. */
static uint32_t pio_hdmi_frames(void) { return hdmi_frame_count; }

const ui_video_backend_t ui_video_backend_pio_hdmi = {
    .name     = "PIO HDMI 640x480",
    .mode     = VIDEO_HDMI,
    .init     = pio_hdmi_init,
    /* No shutdown, for the same reason as the others: unwinding the DMA
     * chain, the exclusive handler and core 1 is more risk than the
     * reboot ui_video_switch() does instead. */
    .shutdown = NULL,
    .present  = pio_hdmi_present,
    .frames   = pio_hdmi_frames,
};
